# Generated by Django 4.2.3 on 2023-07-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
